spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/test_oop
spring.datasource.username=postgres
spring.datasource.password=1234
spring.sql.init.platform=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

jwt.secret=dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIGp3dCB0b2tlbiBnZW5lcmF0aW9u
jwt.expiration=86400000

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=3a333ec42d7723
spring.mail.password=a2daf2eca2800c
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

openrouteservice.api-key=YOUR_API_KEY_HERE